# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LidarGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sainWindow(object):
    def setupUi(self, sainWindow):
        sainWindow.setObjectName("sainWindow")
        sainWindow.resize(506, 566)
        self.centralwidget = QtWidgets.QWidget(sainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 110, 471, 101))
        self.groupBox.setObjectName("groupBox")
        self.TeleAElineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.TeleAElineEdit.setGeometry(QtCore.QRect(60, 28, 391, 21))
        self.TeleAElineEdit.setObjectName("TeleAElineEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 21, 16))
        self.label.setObjectName("label")
        self.TeleGo_Button = QtWidgets.QPushButton(self.groupBox)
        self.TeleGo_Button.setGeometry(QtCore.QRect(340, 60, 113, 32))
        self.TeleGo_Button.setObjectName("TeleGo_Button")
        self.TelsSave_Button = QtWidgets.QPushButton(self.groupBox)
        self.TelsSave_Button.setGeometry(QtCore.QRect(230, 60, 113, 32))
        self.TelsSave_Button.setObjectName("TelsSave_Button")
        self.TeleLoadButton = QtWidgets.QPushButton(self.groupBox)
        self.TeleLoadButton.setGeometry(QtCore.QRect(120, 60, 113, 32))
        self.TeleLoadButton.setObjectName("TeleLoadButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 471, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 230, 471, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 451, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Size_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.Size_comboBox.setObjectName("Size_comboBox")
        self.Size_comboBox.addItem("")
        self.Size_comboBox.addItem("")
        self.Size_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.Size_comboBox)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.Tpix_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.Tpix_lineEdit.setObjectName("Tpix_lineEdit")
        self.horizontalLayout.addWidget(self.Tpix_lineEdit)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.Twait_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.Twait_lineEdit.setObjectName("Twait_lineEdit")
        self.horizontalLayout.addWidget(self.Twait_lineEdit)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 451, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.SP_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.SP_lineEdit.setObjectName("SP_lineEdit")
        self.horizontalLayout_2.addWidget(self.SP_lineEdit)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.period = QtWidgets.QLabel(self.layoutWidget1)
        self.period.setAutoFillBackground(False)
        self.period.setObjectName("period")
        self.horizontalLayout_2.addWidget(self.period)
        self.ThreeD_checkBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ThreeD_checkBox.setObjectName("ThreeD_checkBox")
        self.horizontalLayout_2.addWidget(self.ThreeD_checkBox)
        self.Stic_checkBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.Stic_checkBox.setChecked(True)
        self.Stic_checkBox.setObjectName("Stic_checkBox")
        self.horizontalLayout_2.addWidget(self.Stic_checkBox)
        self.TpSet_Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.TpSet_Button.setObjectName("TpSet_Button")
        self.horizontalLayout_2.addWidget(self.TpSet_Button)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(280, 140, 186, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Stop_Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.Stop_Button.setObjectName("Stop_Button")
        self.horizontalLayout_6.addWidget(self.Stop_Button)
        self.Start_Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.Start_Button.setObjectName("Start_Button")
        self.horizontalLayout_6.addWidget(self.Start_Button)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 100, 451, 32))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SateInfo = QtWidgets.QLabel(self.layoutWidget3)
        self.SateInfo.setAutoFillBackground(False)
        self.SateInfo.setObjectName("SateInfo")
        self.horizontalLayout_3.addWidget(self.SateInfo)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget3)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.TpGo_Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.TpGo_Button.setObjectName("TpGo_Button")
        self.horizontalLayout_3.addWidget(self.TpGo_Button)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 410, 471, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 70, 451, 41))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.ThreeD_Draw_lineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.ThreeD_Draw_lineEdit.setObjectName("ThreeD_Draw_lineEdit")
        self.horizontalLayout_5.addWidget(self.ThreeD_Draw_lineEdit)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 30, 451, 41))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.Puzzle_lineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.Puzzle_lineEdit.setObjectName("Puzzle_lineEdit")
        self.horizontalLayout_4.addWidget(self.Puzzle_lineEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        sainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 22))
        self.menubar.setObjectName("menubar")
        sainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sainWindow)
        self.statusbar.setObjectName("statusbar")
        sainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(sainWindow)
        self.TeleGo_Button.clicked.connect(sainWindow.Telescope_bottonClick)
        self.TpSet_Button.clicked.connect(sainWindow.Takephotos_Set_bottom)
        self.TpGo_Button.clicked.connect(sainWindow.Takephoto_Go_botton)
        self.Start_Button.clicked.connect(sainWindow.Takephoto_Start_Button)
        self.Stop_Button.clicked.connect(sainWindow.Takephoto_Stop_botton)
        self.pushButton_5.clicked.connect(sainWindow.Process_Go1_botton)
        self.pushButton_6.clicked.connect(sainWindow.Process_Go2_botton)
        self.TelsSave_Button.clicked.connect(sainWindow.Telescope_Save_botton)
        QtCore.QMetaObject.connectSlotsByName(sainWindow)

    def retranslateUi(self, sainWindow):
        _translate = QtCore.QCoreApplication.translate
        sainWindow.setWindowTitle(_translate("sainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("sainWindow", "Telescope"))
        self.label.setText(_translate("sainWindow", "A,E"))
        self.TeleGo_Button.setText(_translate("sainWindow", "Go"))
        self.TelsSave_Button.setText(_translate("sainWindow", "Save"))
        self.TeleLoadButton.setText(_translate("sainWindow", "Load"))
        self.groupBox_2.setTitle(_translate("sainWindow", "Device"))
        self.groupBox_3.setTitle(_translate("sainWindow", "Take photos"))
        self.label_2.setText(_translate("sainWindow", "Size"))
        self.Size_comboBox.setItemText(0, _translate("sainWindow", "64"))
        self.Size_comboBox.setItemText(1, _translate("sainWindow", "32"))
        self.Size_comboBox.setItemText(2, _translate("sainWindow", "128"))
        self.label_3.setText(_translate("sainWindow", "T_pix_ms"))
        self.Tpix_lineEdit.setText(_translate("sainWindow", "20"))
        self.label_4.setText(_translate("sainWindow", "T_wait"))
        self.Twait_lineEdit.setText(_translate("sainWindow", "0"))
        self.label_5.setText(_translate("sainWindow", "SubPicNum"))
        self.SP_lineEdit.setText(_translate("sainWindow", "5"))
        self.label_6.setText(_translate("sainWindow", "period"))
        self.period.setText(_translate("sainWindow", "81.96"))
        self.ThreeD_checkBox.setText(_translate("sainWindow", "3D"))
        self.Stic_checkBox.setText(_translate("sainWindow", "Stic"))
        self.TpSet_Button.setText(_translate("sainWindow", "Set"))
        self.Stop_Button.setText(_translate("sainWindow", "Stop"))
        self.Start_Button.setText(_translate("sainWindow", "Start"))
        self.SateInfo.setText(_translate("sainWindow", "Size:64X64 20ms Stic"))
        self.TpGo_Button.setText(_translate("sainWindow", "Go"))
        self.groupBox_4.setTitle(_translate("sainWindow", "Data Procesing"))
        self.label_8.setText(_translate("sainWindow", "3D Draw"))
        self.pushButton_6.setText(_translate("sainWindow", "Go"))
        self.label_7.setText(_translate("sainWindow", "Puzzle  "))
        self.pushButton_5.setText(_translate("sainWindow", "Go"))

